name: CI via Workflow Reutilizável

on:
  push:
    branches: [ main ]        
  pull_request:
    branches: [ main ]

jobs:
  login:
    uses: marieliburi/php-workflows/.github/workflows/login.yml@master
